variable "valtix_api_key_file" {}
variable "gcp_key_file" {}
variable "gcp_project_id" {}
variable "valtix_account_name" {}
variable "region" {}
variable "zone" {}
variable "prefix" {}
variable "service_account_email" {}
variable "spoke_vpcs" {}
